; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25547.0 

	TITLE	D:\Paul\Documents\Raven\Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
